name: PR update
on:
  pull_request:
    types: [opened]


jobs:
  update_pr:
  name: Update PR
    runs-on: ubuntu-latest
    steps:
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          base-branch-regex: '[A-Za-z\d-_.\\/]+'
          head-branch-regex: '^([A-Za-z])+-\d+'
          title-template: '%headbranch%: '
          body-template: |
            Jira issue: %headbranch%
            ---
          body-update-action: 'prefix'
          body-uppercase-base-match: false